// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdZ3iapqQSl6ki1IbenjqtzQSHZjcAA00',
    appId: '1:102943424137:android:692ee7fabb46f671e29058',
    messagingSenderId: '102943424137',
    projectId: 'vtccapp-ee91f',
    storageBucket: 'vtccapp-ee91f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKSn4kT36URyK2k8LlkB8Lh1S4OV8g53k',
    appId: '1:102943424137:ios:ef3632856b875f49e29058',
    messagingSenderId: '102943424137',
    projectId: 'vtccapp-ee91f',
    storageBucket: 'vtccapp-ee91f.appspot.com',
    iosClientId: '316556559956-tbct2qqa883obptg75sftv05gb5pvcjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}